// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxLnNthlFw4qOagF1L_0hiWim4CalR3DM',
    appId: '1:590609911321:web:0f6f6be8d9eeac5f5b2488',
    messagingSenderId: '590609911321',
    projectId: 'flutter-task-7',
    authDomain: 'flutter-task-7.firebaseapp.com',
    storageBucket: 'flutter-task-7.appspot.com',
    measurementId: 'G-3KL01TYXH2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFabKhjSCI8GQHh7ri9CIaQQwqTPtMI1Q',
    appId: '1:590609911321:android:3137f3dfb3973bbe5b2488',
    messagingSenderId: '590609911321',
    projectId: 'flutter-task-7',
    storageBucket: 'flutter-task-7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFW1X4wunUY5ym3C2JQNmd7KAwY7wawo0',
    appId: '1:590609911321:ios:3ff4af9281feae875b2488',
    messagingSenderId: '590609911321',
    projectId: 'flutter-task-7',
    storageBucket: 'flutter-task-7.appspot.com',
    iosClientId: '590609911321-hfi4e0aofiq1rogfd98vhujsogcg4rnc.apps.googleusercontent.com',
    iosBundleId: 'com.example.layerArchitectureTemplate',
  );
}
